language: generic

os: linux

services:
  - docker

before_install:
  - docker build -t forestfrag3d .
  - docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=uid=1000 data-volume
  - docker run --rm -v data-volume:/data -it forestfrag3d /code/run.sh test

notifications:
  email:
    recipients:
      - wenzeslaus@gmail.com
    on_success: change
    on_failure: always
